# Introduction to Python
Run the hidden code cell below to import the data used in this course.

In [1]:
# Importing course packages; you can add more too!
import numpy as np
import math

# Import columns as numpy arrays
baseball_names = np.genfromtxt(
    fname="baseball.csv",  # This is the filename
    delimiter=",",  # The file is comma-separated
    usecols=0,  # Use the first column
    skip_header=1,  # Skip the first line
    dtype=str,  # This column contains strings
)
baseball_heights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=3, skip_header=1
)
baseball_weights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=4, skip_header=1
)
baseball_ages = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=5, skip_header=1
)

soccer_names = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=1,
    skip_header=1,
    dtype=str,
    encoding="utf", 
)
soccer_ratings = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=2,
    skip_header=1,
    encoding="utf", 
)
soccer_positions = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=3,
    skip_header=1,
    encoding="utf", 
    dtype=str,
)
soccer_heights = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=4,
    skip_header=1,
    encoding="utf", 
)
soccer_shooting = np.genfromtxt(
    fname="soccer.csv",
    delimiter=",",
    usecols=8,
    skip_header=1,
    encoding="utf", 
)

## Take Notes

Add notes about the concepts you've learned and code cells with code you want to keep.

1. variables are used to store values, which can be reused at a later time.
2. print() --> inbuilt python function used to display a command.
3. List can contain any datatype discussed (str, int, float, bool) and even another list.
4. subsetting a list --> `listname[index]`, use the square braces and enter the index of the value you need.
5. slicing --> `listobject[start : end-1 ]`, use this to slice a list fromt the start without including the end.
6. list manipulation --> (a) changing a value in the list (b) deleting a value in the list (c) adding new values to the list
7. an `iterable` is any collection of object like list()
8. functions (creat) --> a piece of reusable code
9. method --> basically a function associated with a class/object
10. sorted(iterable*, reverse=bool) --> an inbuilt function that sorts an iterable either in ascending or descending by setting the reverse option to true or false.
11. methods: append() <- adds an item to the end of a list | len() <-- counts the number of items in an object | count() <-- returns the number of appearance of a specific item in an object
12. packages --> a file that contains a set of functions and methods eg: `numpy`
13. Numpy --> a library used for working with arrays (how to call) `import numpy` or using the globally accepted alias `import numpy as np`.
14. convert list -> numpy array: `numpy.array(list_object)`
15. `numpyarray.shape` --> returns the ndim shape of a numpy object. first item is the number of row and the second is the number of columns.
16. basic stats with numpy: np.mean(), np.median(), np.corrcoef(), np.sum(), np.random.normal()

In [2]:
fname = 'jesse'
mylist = [[fname, 100+30], ['annan', 5.7], [True, False]]
print(mylist)
print(mylist[2])
print(mylist[:2]) # starts slicing from index zero
print(mylist[-1]) # negative index slices from the end

# list manipulation
mylist[-1] = [False, False]
mylist += [['degree', 'msc']]
del(mylist[1])
mylist.reverse()
print(mylist)
import numpy as np
np_mylist = np.array(mylist)
print(np_mylist)
print(np_mylist.shape)

# stats with numpy
height = np.array([1.4, 5.3, 5., 2.3, 1.7])
weight = np.array([1., 2.3, 1.6, 1.7, 1.])
bmi = weight / height**2
print(bmi)
correlation = np.corrcoef(height, weight)
print(correlation)
print(np.mean(bmi))

[['jesse', 130], ['annan', 5.7], [True, False]]
[True, False]
[['jesse', 130], ['annan', 5.7]]
[True, False]
[['degree', 'msc'], [False, False], ['jesse', 130]]
[['degree' 'msc']
 ['False' 'False']
 ['jesse' '130']]
(3, 2)
[0.51020408 0.08187967 0.064      0.32136106 0.34602076]
[[1.         0.81999478]
 [0.81999478 1.        ]]
0.26469311479215446


## Explore Datasets
Use the arrays imported in the first cell to explore the data and practice your skills!
- Print out the weight of the first ten baseball players. 
- What is the median weight of all baseball players in the data? 
- Print out the names of all players with a height greater than 80 (heights are in inches). 
- Who is taller on average? Baseball players or soccer players? Keep in mind that baseball heights are stored in inches!
- The values in `soccer_shooting` are decimals. Convert them to whole numbers (e.g., 0.98 becomes 98).
- Do taller players get higher ratings? Calculate the correlation between `soccer_ratings` and `soccer_heights` to find out!
- What is the average rating for attacking players (`'A'`)?

In [3]:
# weight of the first 10 players
baseball_weights_f10 = baseball_weights[:10]
print(baseball_weights_f10)

[180. 215. 210. 210. 188. 176. 209. 200. 231. 180.]


In [4]:
# median weight of all baseball players
baseball_weights_med = np.median(baseball_weights)
print(baseball_weights_med)

200.0


In [5]:
# baseball players taller than 80 inches
height_over80b = baseball_heights > 80
baseball_players_over80 = baseball_names[height_over80b]
print('Baseball players over 80 inches: ' + str(baseball_players_over80))

Baseball players over 80 inches: ['Andrew_Sisco' 'Randy_Johnson' 'Mark_Hendrickson' 'Chris_Young'
 'Jon_Rauch']


In [6]:
baseball_heights

array([74., 74., 72., ..., 75., 75., 73.])

In [7]:
# convert cm -> inch: 1 cm == 0.3937008 inch
soccer_heights_in = soccer_heights * 0.3937008

# mean of both baseball and soccer heights
baseball_heights_avg = np.mean(baseball_heights)
soccer_heights_avg = np.mean(soccer_heights_in)
print(baseball_heights_avg, soccer_heights_avg) # baseball players are taller on the avarage

73.6896551724138 71.55528727894202


In [8]:
soccer_shooting * 100

array([nan, 65., 54., ..., 40., 48., 56.])

In [9]:
# correlation between soccer rating and soccer height
corr = np.corrcoef(soccer_heights, soccer_ratings)
print(corr) # Nope... taller players tend to have low rating

[[ 1.         -0.00610858]
 [-0.00610858  1.        ]]


In [10]:
# attacking player
attacker = soccer_positions == 'A'
attack_rating = soccer_ratings[attacker]
attack_rating_avg = np.mean(attack_rating)
print(attack_rating_avg)

67.26080691642652
